# Trigger workflow on tag created in master branch
on:
  push:
    tags:
      - 'v*'

name: Deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.repository == 'acs-upb-mobile/acs-upb-mobile'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Get packages
        run: flutter pub get

      - name: Enable web
        run: flutter config --enable-web

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web --release

      - name: Fetch time_machine
        run: git clone https://github.com/Dana-Ferguson/time_machine

      - name: Copy time_machine data to the build area
        run: mkdir -p build/web/packages/time_machine/data && cp -R time_machine/lib/data build/web/packages/time_machine

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build APK
        run: flutter build apk --release

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.RELEASE_TOKEN }}